spring:
  application:
    name: oauth2
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
#  redis:
#    lettuce:
#      pool:
#        min-idle: 0
#        max-idle: 8
#        max-wait: -1ms
#        max-active: 8
#    cluster:
#      nodes: my.redis.com:7001,my.redis.com:7002,my.redis.com:7003,my.redis.com:7004,my.redis.com:7005,my.redis.com:7006
#    password: yang123(*&
dubbo:
  scan:
    base-packages: com.study.shop.oauth2.controller, com.study.shop.oauth2.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://192.168.200.128
    port: 8848
server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"

business:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  sentinel:
    enabled: true
