spring:
  application:
    name: user-provider
  main:
    allow-bean-definition-overriding: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.243.204:3306/secondMall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: Tiger
    password: yang526163
    hikari:
      auto-commit: true
      minimum-idle: 5
      idle-timeout: 60000
      maximum-pool-size: 10
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 6000
      connection-test-query: SELECT 1
dubbo:
  scan:
    base-packages: com.study.shop.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://localhost
    port: 8848
mybatis:
  type-aliases-package: com.study.shop.provider.domain
  mapper-locations: classpath:com.study.shop.provider.mapper/*.xml
logging:
  level:
    com:
      study:
        shop:
          provider:
            mapper: DEBUG
