base:
  config:
    oauth:
      hostname: localhost
      port: 9001
    nacos:
      hostname: 192.168.200.128
      port: 8848
    sentile:
      hostname: 192.168.200.128
      port: 8080
spring:
  application:
    name: goods
  main:
    #解决重复bean定义
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
    sentinel:
      transport:
        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}
    stream:
      bindings:
        shop:
          content-type: text/plain
          destination: shopTopic
        order:
          consumer:
            concurrency: 20
          content-type: application/json
          destination: shopTopic
          group: shop-group
      rocketmq:
        binder:
          name-server: 192.168.200.128:9876
        #自定义的名称 对应spring.cloud.stream.bindings.output1
        bindings:
          shop:
            producer:
              group: shop-group
              transactional: true
          order:
            consumer:
              broadcasting: false
              #              sql: 'index >= 600'
              tags: create_order || check_order
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token
      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize
    resource:
      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token

dubbo:
  scan:
    base-packages: com.study.shop.business.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

server:
  port: 9004

feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
