name: Cloud CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ${{secrets.MAVEN_ID}}
          server-username: ${{secrets.DOCKER_USERNAME}} # env variable for username in deploy
          server-password: ${{secrets.DOCKER_PASSWORD}} # env variable for token in deploy
      - name: Build
        run: mvn package
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build Gateway
#        run: mvn compile jib:build -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
#        working-directory: ./gateway
#  classification_provider:
#    needs: gateway
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build classification_provider
#        run: mvn compile jib:build -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
#        working-directory: ./provider/classification-provider-service
#  goods_provider:
#    needs: gateway
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build goods_provider
#        run: mvn compile jib:build -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
#        working-directory: ./provider/goods-provider-service
#  user_provider:
#    needs: gateway
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build user_provider
#        run: mvn compile jib:build -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
#        working-directory: ./provider/user-provider-service
#  cloud:
#    needs: gateway
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build cloud
#        run: mvn compile jib:build -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
#        working-directory: ./cloud/upload-service
#  classification:
#    needs: [gateway,classification_provider]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build classification
#        run: mvn compile jib:build -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
#        working-directory: ./business/classification-service
#  goods:
#    needs: [gateway,goods_provider]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build goods
#        run: mvn compile jib:build -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
#        working-directory: ./business/goods-service
#  oauth2:
#    needs: [gateway,user_provider]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build oauth2
#        run: mvn compile jib:build -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
#        working-directory: ./business/oauth2-service
