name: Cloud CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        working-directory: ./gateway
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Gateway
        run: mvn compile jib:build \
          -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} \
          -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
  classification_provider:
    needs: gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        working-directory: ./provider/classification-provider-service
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build classification_provider
        run: mvn compile jib:build \
          -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} \
          -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
  goods_provider:
    needs: gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        working-directory: ./provider/goods-provider-service
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build goods_provider
        run: mvn compile jib:build \
          -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} \
          -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
  user_provider:
    needs: gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        working-directory: ./provider/user-provider-service
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build user_provider
        run: mvn compile jib:build \
          -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} \
          -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
  cloud:
    needs: gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        working-directory: ./cloud/upload-service
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build cloud
        run: mvn compile jib:build \
          -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} \
          -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
  classification:
    needs: [gateway,classification_provider]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        working-directory: ./business/classification-service
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build classification
        run: mvn compile jib:build \
          -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} \
          -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
  goods:
    needs: [gateway,goods_provider]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        working-directory: ./business/goods-service
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build goods
        run: mvn compile jib:build \
          -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} \
          -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
  oauth2:
    needs: [gateway,goodsuser_provider]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        working-directory: ./business/oauth2-service
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build oauth2
        run: mvn compile jib:build \
          -Djib.from.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.from.auth.password=${{secrets.DOCKER_PASSWORD}} \
          -Djib.to.auth.username=${{secrets.DOCKER_USERNAME}} \
          -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}}
