name: Cloud CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: registry.cn-hangzhou.aliyuncs.com
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
      - name: Build
        run: mvn package
        cache: true
        env:
          MAVEN_USERNAME: ${{secrets.DOCKER_USERNAME}}
          MAVEN_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
